### ISSUE TITLE
encodeToRot13

### ISSUE THREAD

**Issue by aorgish** [alenka1710/js-assignments#3]
https://github.com/alenka1710/js-assignments/blob/0600f3a9b8103bca81335c0a4ed41a84bdfc74cf/task/01-strings-tasks.js#L226-L251

Тут лучше попробовать метод `string.replace`

Плюс много магических цифр: 65, 90, 26, 97, 122 . Очень тяжело понимать код, когда там такие цифры. Для того, чтобы было понятнее вместо магических цифр принято использовать константы:

```
  const lettersCount = 26;
  const lowercaseOffset = 'a'.charCodeAt(0);
  const uppercaseOffset = 'A'.charCodeAt(0);
```

**Comment by alionaSipchuk** [comment]
а в лабах по КИТу преподаватель требовал именно через коды, вот поэтому делала по аналогии))
